# Generated by Django 4.1.3 on 2022-12-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=40)),
                ('publisher', models.CharField(max_length=100)),
                ('no_lines', models.IntegerField()),
            ],
        ),
    ]
